version: '3.7'
services:
  kafka:
    container_name: kafka_local
    image: wurstmeister/kafka
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      - ADVERTISED_PORT=9092
    hostname: http://192.168.99.100